"""debug in posts

Revision ID: d08765e4453a
Revises: ad3fae65aca5
Create Date: 2025-05-09 21:38:01.536960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08765e4453a'
down_revision: Union[str, None] = 'ad3fae65aca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('posts', 'image_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'title_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'from_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'from_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'title_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'image_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
