"""corrected table posts

Revision ID: 9be5d0c8556d
Revises: ad3fae65aca5
Create Date: 2025-05-05 08:44:38.335890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be5d0c8556d'
down_revision: Union[str, None] = 'ad3fae65aca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'image_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'image_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
